In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [4]:
dataset=dataset.iloc[:,2:]

In [5]:
dataset.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [6]:
x=dataset.drop('Purchased',axis=1)
y=dataset['Purchased']

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

# StandardScaler

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [9]:
scaler.mean_

array([3.78642857e+01, 6.98071429e+04])

In [10]:
x_train

     Age  EstimatedSalary
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000
..   ...              ...
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[280 rows x 2 columns]

In [11]:
x_train_scaled

array([[-1.1631724 , -1.5849703 ],
       [ 2.17018137,  0.93098672],
       [ 0.0133054 ,  1.22017719],
       [ 0.20938504,  1.07558195],
       [ 0.40546467, -0.48604654],
       [-0.28081405, -0.31253226],
       [ 0.99370357, -0.8330751 ],
       [ 0.99370357,  1.8563962 ],
       [ 0.0133054 ,  1.24909623],
       [-0.86905295,  2.26126285],
       [-1.1631724 , -1.5849703 ],
       [ 2.17018137, -0.80415605],
       [-1.35925203, -1.46929411],
       [ 0.40546467,  2.2901819 ],
       [ 0.79762394,  0.75747245],
       [-0.96709276, -0.31253226],
       [ 0.11134522,  0.75747245],
       [-0.96709276,  0.55503912],
       [ 0.30742485,  0.06341534],
       [ 0.69958412, -1.26686079],
       [-0.47689368, -0.0233418 ],
       [-1.7514113 ,  0.3526058 ],
       [-0.67297331,  0.12125343],
       [ 0.40546467,  0.29476771],
       [-0.28081405,  0.06341534],
       [-0.47689368,  2.2901819 ],
       [ 0.20938504,  0.03449629],
       [ 1.28782302,  2.20342476],
       [ 0.79762394,  0.26584866],
       [-0.28081405,  0.15017248],
       [ 0.0133054 , -0.54388463],
       [-0.18277423,  0.15017248],
       [-0.08473441,  0.23692961],
       [ 0.0133054 , -0.25469417],
       [ 2.17018137,  1.104501  ],
       [-1.7514113 ,  0.3526058 ],
       [ 1.87606192,  0.12125343],
       [ 0.40546467, -0.13901799],
       [-1.1631724 ,  0.29476771],
       [ 0.79762394,  1.36477242],
       [-0.28081405, -0.25469417],
       [-1.65337148, -0.05226085],
       [-0.96709276, -0.74631796],
       [ 0.30742485,  0.49720103],
       [-0.08473441, -1.06442747],
       [-1.06513258,  0.58395817],
       [ 0.11134522, -0.80415605],
       [-0.96709276,  1.53828669],
       [-0.67297331,  1.39369146],
       [-1.26121221,  0.49720103],
       [-0.28081405,  0.03449629],
       [-0.08473441,  0.00557724],
       [-0.28081405, -0.89091319],
       [ 0.89566375, -1.35361793],
       [-0.28081405,  2.2323438 ],
       [ 0.99370357,  1.97207239],
       [-1.1631724 ,  0.46828198],
       [-1.26121221,  0.26584866],
       [ 1.38586284,  1.97207239],
       [ 1.28782302, -1.35361793],
       [-0.28081405, -0.28361322],
       [-0.47689368,  1.24909623],
       [-0.77101313,  1.07558195],
       [ 0.99370357, -1.06442747],
       [ 0.30742485,  0.29476771],
       [ 0.99370357,  0.75747245],
       [-0.67297331, -1.49821316],
       [-0.67297331,  0.03449629],
       [ 0.50350449,  1.71180097],
       [ 2.07214155,  0.17909152],
       [-1.94749093, -0.74631796],
       [-0.18277423,  1.39369146],
       [ 0.40546467,  0.58395817],
       [ 0.89566375, -1.1511846 ],
       [-1.1631724 , -0.775237  ],
       [ 0.20938504,  0.23692961],
       [ 0.79762394, -0.31253226],
       [ 2.07214155, -0.80415605],
       [ 0.79762394,  0.12125343],
       [-0.28081405,  0.61287722],
       [-0.96709276, -0.31253226],
       [ 0.20938504, -0.37037036],
       [ 2.07214155,  2.11666762],
       [ 1.87606192, -1.26686079],
       [ 1.38586284, -0.91983223],
       [ 0.89566375,  1.24909623],
       [ 1.48390265,  2.11666762],
       [-0.28081405, -1.23794174],
       [ 1.97410174,  0.90206768],
       [ 0.69958412, -0.71739891],
       [-1.45729185,  0.3526058 ],
       [ 0.79762394, -1.35361793],
       [ 0.40546467, -0.13901799],
       [-0.96709276,  0.41044389],
       [ 0.0133054 , -0.31253226],
       [-1.1631724 ,  0.41044389],
       [-0.86905295, -1.2090227 ],
       [-0.08473441,  0.03449629],
       [-1.55533166, -0.42820845],
       [ 0.99370357, -1.00658937],
       [ 1.09174339, -1.2090227 ],
       [ 0.0133054 , -0.13901799],
       [-1.06513258, -1.52713221],
       [ 0.79762394, -1.2090227 ],
       [ 0.99370357,  2.05882953],
       [-1.1631724 , -1.52713221],
       [-0.28081405,  0.78639149],
       [ 0.11134522, -0.31253226],
       [-1.35925203, -1.23794174],
       [-0.5749335 , -1.49821316],
       [ 0.79762394,  0.52612008],
       [-0.28081405, -0.34145131],
       [ 1.7780221 , -0.28361322],
       [ 0.89566375, -1.03550842],
       [ 0.20938504,  0.06341534],
       [-0.5749335 ,  0.87314863],
       [-1.84945111, -1.41145602],
       [-1.26121221,  0.58395817],
       [-0.28081405,  0.52612008],
       [-0.96709276, -1.09334651],
       [ 1.1897832 , -1.44037507],
       [ 0.20938504, -0.31253226],
       [ 1.1897832 , -0.74631796],
       [-0.28081405,  0.06341534],
       [ 0.20938504,  2.08774857],
       [ 0.79762394, -1.09334651],
       [ 0.11134522,  0.03449629],
       [-1.7514113 ,  0.12125343],
       [-0.86905295,  0.15017248],
       [-0.67297331,  0.17909152],
       [ 0.89566375, -1.29577984],
       [ 0.20938504, -0.25469417],
       [-0.37885386,  1.22017719],
       [ 0.0133054 ,  0.29476771],
       [ 0.40546467,  0.15017248],
       [ 0.89566375, -0.65956082],
       [ 0.11134522,  0.15017248],
       [-1.84945111, -1.29577984],
       [-0.08473441,  0.29476771],
       [-0.18277423, -0.28361322],
       [ 0.30742485, -0.51496559],
       [-0.18277423,  1.59612479],
       [ 0.99370357, -1.18010365],
       [-0.18277423,  1.62504383],
       [ 1.28782302,  1.8563962 ],
       [-1.06513258, -0.37037036],
       [ 0.0133054 ,  0.03449629],
       [ 0.11134522, -0.25469417],
       [-1.55533166, -1.23794174],
       [-0.47689368, -0.28361322],
       [ 0.99370357,  0.12125343],
       [ 1.97410174, -1.35361793],
       [ 1.48390265,  0.06341534],
       [-0.5749335 ,  1.36477242],
       [ 1.58194247,  0.00557724],
       [-0.77101313,  0.29476771],
       [ 1.97410174,  0.7285534 ],
       [-1.1631724 , -0.51496559],
       [ 0.69958412,  0.26584866],
       [-1.35925203, -0.42820845],
       [ 0.20938504,  0.15017248],
       [-0.47689368, -1.2090227 ],
       [ 0.6015443 ,  2.00099143],
       [-1.55533166, -1.49821316],
       [-0.47689368, -0.54388463],
       [ 0.50350449,  1.82747716],
       [-1.35925203, -1.09334651],
       [ 0.79762394, -1.38253697],
       [-0.28081405, -0.42820845],
       [ 1.58194247,  0.98882482],
       [ 0.99370357,  1.42261051],
       [-0.28081405, -0.48604654],
       [-0.08473441,  2.14558666],
       [-1.45729185, -0.11009894],
       [-0.08473441,  1.94315334],
       [-0.67297331, -0.34145131],
       [-0.47689368, -0.8330751 ],
       [ 0.69958412, -1.38253697],
       [-0.77101313, -1.5849703 ],
       [-1.84945111, -1.46929411],
       [ 1.09174339,  0.12125343],
       [ 0.11134522,  1.50936765],
       [-0.28081405,  0.09233438],
       [ 0.11134522,  0.03449629],
       [-1.35925203, -1.35361793],
       [ 0.30742485,  0.06341534],
       [-0.86905295,  0.38152485],
       [ 1.58194247, -1.26686079],
       [-0.28081405, -0.74631796],
       [-0.08473441,  0.15017248],
       [-0.86905295, -0.65956082],
       [-0.67297331, -0.05226085],
       [ 0.40546467, -0.45712749],
       [-0.77101313,  1.88531525],
       [ 1.38586284,  1.27801528],
       [ 1.1897832 , -0.97767033],
       [ 1.7780221 ,  1.82747716],
       [-0.86905295, -0.25469417],
       [-0.77101313,  0.55503912],
       [-1.1631724 , -1.55605125],
       [-0.47689368, -1.12226556],
       [ 0.30742485,  0.06341534],
       [-0.18277423, -1.06442747],
       [ 1.67998229,  1.59612479],
       [ 0.99370357,  1.76963906],
       [ 0.30742485,  0.03449629],
       [-0.77101313, -0.22577513],
       [-0.08473441,  0.06341534],
       [ 0.30742485, -0.19685608],
       [ 1.97410174, -0.65956082],
       [-0.77101313,  1.33585337],
       [-1.7514113 , -0.60172273],
       [-0.08473441,  0.12125343],
       [ 0.30742485, -0.31253226],
       [ 1.09174339,  0.55503912],
       [-0.96709276,  0.26584866],
       [ 1.48390265,  0.3526058 ],
       [ 0.20938504, -0.37037036],
       [ 2.17018137, -1.03550842],
       [-0.28081405,  1.104501  ],
       [-1.65337148,  0.06341534],
       [ 0.0133054 ,  0.03449629],
       [ 0.11134522,  1.04666291],
       [-0.08473441, -0.37037036],
       [-1.1631724 ,  0.06341534],
       [-0.28081405, -1.35361793],
       [ 1.58194247,  1.104501  ],
       [-0.77101313, -1.52713221],
       [ 0.11134522,  1.8563962 ],
       [-0.86905295, -0.775237  ],
       [-0.47689368, -0.775237  ],
       [-0.28081405, -0.91983223],
       [ 0.30742485, -0.71739891],
       [ 0.30742485,  0.06341534],
       [ 0.11134522,  1.8563962 ],
       [-1.06513258,  1.94315334],
       [-1.65337148, -1.55605125],
       [-1.1631724 , -1.09334651],
       [-0.67297331, -0.11009894],
       [ 0.11134522,  0.09233438],
       [ 0.30742485,  0.26584866],
       [ 0.89566375, -0.57280368],
       [ 0.30742485, -1.1511846 ],
       [-0.08473441,  0.67071531],
       [ 2.17018137, -0.68847986],
       [-1.26121221, -1.38253697],
       [-0.96709276, -0.94875128],
       [ 0.0133054 , -0.42820845],
       [-0.18277423, -0.45712749],
       [-1.7514113 , -0.97767033],
       [ 1.7780221 ,  0.98882482],
       [ 0.20938504, -0.37037036],
       [ 0.40546467,  1.104501  ],
       [-1.7514113 , -1.35361793],
       [ 0.20938504, -0.13901799],
       [ 0.89566375, -1.44037507],
       [-1.94749093,  0.46828198],
       [-0.28081405,  0.26584866],
       [ 1.87606192, -1.06442747],
       [-0.37885386,  0.06341534],
       [ 1.09174339, -0.89091319],
       [-1.06513258, -1.12226556],
       [-1.84945111,  0.00557724],
       [ 0.11134522,  0.26584866],
       [-1.1631724 ,  0.32368675],
       [-1.26121221,  0.29476771],
       [-0.96709276,  0.43936294],
       [ 1.67998229, -0.89091319],
       [ 1.1897832 ,  0.52612008],
       [ 1.09174339,  0.52612008],
       [ 1.38586284,  2.31910094],
       [-0.28081405, -0.13901799],
       [ 0.40546467, -0.45712749],
       [-0.37885386, -0.775237  ],
       [-0.08473441, -0.51496559],
       [ 0.99370357, -1.1511846 ],
       [-0.86905295, -0.775237  ],
       [-0.18277423, -0.51496559],
       [-1.06513258, -0.45712749],
       [-1.1631724 ,  1.39369146]])

# importance of Scaling

In [12]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled  = pd.DataFrame(x_test_scaled,  columns=x_test.columns)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
lr=KNeighborsClassifier()
lr_scaled=KNeighborsClassifier()

In [15]:
lr.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
lr_scaled.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [17]:
y_pred=lr.predict(x_test)

In [18]:
y_pred_scaled=lr_scaled.predict(x_test_scaled)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print("Actual",accuracy_score(y_test,y_pred))
print("Scaled",accuracy_score(y_test,y_pred_scaled))
# Scaling matters for → KNN, SVM, Neural Networks (distance/gradient based)

Actual 0.825
Scaled 0.9166666666666666

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
dt=DecisionTreeClassifier()
dt_scaled=DecisionTreeClassifier()

In [23]:
dt.fit(x_train,y_train)
dt_scaled.fit(x_train_scaled,y_train)

DecisionTreeClassifier()

In [24]:
y_pred=dt.predict(x_test)
y_pred_scaled=dt_scaled.predict(x_test_scaled)

In [25]:

print("Actual",accuracy_score(y_test,y_pred))
print("Scaled",accuracy_score(y_test,y_pred_scaled))

# Scaling doesn't matter for → Decision Tree, Random Forest (split based)

Actual 0.875
Scaled 0.8666666666666667